[package]
name = "rust-api-call"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.132"
serde = {version = "1.0.214", features = ["derive"]}
reqwest = {version = "0.12.9", features = ["json"]}
tokio = {version = "1.35.1", features = ["full"]}
